# NWB exploration

In [1]:
from pynwb import NWBHDF5IO
import numpy as np 

In [8]:
#change pathway as needed
io = NWBHDF5IO('/Users/vanessagutierrez/Desktop/NWB_Test/RVG21/RVG21_B02.nwb', 'r')
nwb = io.read()

In [9]:
nwb

root pynwb.file.NWBFile at 0x140628934884416
Fields:
  acquisition: {
    ECoG <class 'pynwb.ecephys.ElectricalSeries'>
  }
  devices: {
    ECoG <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    ECoG <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experiment_description: This is an acute rat experiment. Auditory stimuli are played to an anesthsized rat and electrophysiological measurements are made auditory cortex
  experimenter: ['Vanessa Gutierrez']
  file_create_date: [datetime.datetime(2021, 9, 7, 14, 35, 56, 402889, tzinfo=tzoffset(None, -25200))]
  identifier: 95c18458-1023-11ec-b0f0-aa665a133c20
  institution: Lawrence Berkeley National Lab
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  lab: Bouchard Lab
  notes: All channels responsed! couple of bad channels, lots of 60Hz due to PZ5 being on, injected ketamine 13 mins before
  pharmacology: Anesthesized with Ketamine (90 mg/kg inducti

In [139]:
nwb_signal_data = nwb.acquisition['ECoG'].data[:]

In [137]:
nwb.acquisition['ECoG'].data[:].T[0]

array([ 1731.07346602,  1404.92890931,  1515.16066544, ...,
       -4128.9488449 , -4073.24806302, -4088.56527452])

In [64]:
trials_df = nwb.trials[:]

In [65]:
trials_df

start_time   stop_time sb    frq  amp
id                                        
0      0.000000    7.930483  b  500.0  6.0
1      7.980483    8.030483  s    500    6
2      8.080483    8.160483  b    500    6
3      8.280515    8.330515  s   3175    6
4      8.380515    8.460515  b   3175    6
..          ...         ... ..    ...  ...
597   97.380925   97.430925  s  20159    4
598   97.480925   97.560925  b  20159    4
599   97.680916   97.730916  s   2000    6
600   97.780916   97.860916  b   2000    6
601   97.860916  101.669929  b   2000    6

[602 rows x 5 columns]

In [66]:
trials_df[['start_time', 'sb']].loc[trials_df['sb'].str.contains('s')]['start_time'][:]

id
1       7.980483
3       8.280515
5       8.580506
7       8.880497
9       9.180488
         ...    
591    96.480911
593    96.780902
595    97.080934
597    97.380925
599    97.680916
Name: start_time, Length: 300, dtype: float64

In [42]:
nwb.intervals['trials']['start_time'][:]

array([ 0.        ,  7.98048256,  8.08048256,  8.28051456,  8.38051456,
        8.5805056 ,  8.6805056 ,  8.88049664,  8.98049664,  9.18048768,
        9.28048768,  9.48051968,  9.58051968,  9.78051072,  9.88051072,
       10.08050176, 10.18050176, 10.3804928 , 10.4804928 , 10.6805248 ,
       10.7805248 , 10.98051584, 11.08051584, 11.28050688, 11.38050688,
       11.58049792, 11.68049792, 11.88052992, 11.98052992, 12.18052096,
       12.28052096, 12.480512  , 12.580512  , 12.78050304, 12.88050304,
       13.08053504, 13.18053504, 13.38052608, 13.48052608, 13.68051712,
       13.78051712, 13.98050816, 14.08050816, 14.28054016, 14.38054016,
       14.5805312 , 14.6805312 , 14.88052224, 14.98052224, 15.18051328,
       15.28051328, 15.48054528, 15.58054528, 15.78053632, 15.88053632,
       16.08052736, 16.18052736, 16.3805184 , 16.4805184 , 16.6805504 ,
       16.7805504 , 16.98054144, 17.08054144, 17.28053248, 17.38053248,
       17.58052352, 17.68052352, 17.88055552, 17.98055552, 18.18

In [35]:
nwbfile_in.acquisition['ECoG'].data[:].shape

(1239166, 128)

In [36]:
nwbfile_in.stimulus

{'stim_onset_marks': stim_onset_marks pynwb.base.TimeSeries at 0x140628039993712
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (1261568,), type "<f4">
   description: Recorded mark that tracks stimulus onsets.
   rate: 12207.03125
   resolution: -1.0
   starting_time: 0.0
   starting_time_unit: seconds
   unit: Volts,
 'stim_waveform': stim_waveform pynwb.base.TimeSeries at 0x140628039993184
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (4800248,), type "<i2">
   description: Auditory stimulus waveform, aligned to neural recording.
   rate: 48000.0
   resolution: -1.0
   starting_time: 2.74766592
   starting_time_unit: seconds
   unit: Volts}

In [37]:
nwbfile_in.stimulus['stim_onset_marks']

stim_onset_marks pynwb.base.TimeSeries at 0x140628039993712
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (1261568,), type "<f4">
  description: Recorded mark that tracks stimulus onsets.
  rate: 12207.03125
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: Volts

In [38]:
nwbfile_in.stimulus['stim_waveform']

stim_waveform pynwb.base.TimeSeries at 0x140628039993184
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (4800248,), type "<i2">
  description: Auditory stimulus waveform, aligned to neural recording.
  rate: 48000.0
  resolution: -1.0
  starting_time: 2.74766592
  starting_time_unit: seconds
  unit: Volts

In [39]:
device = 'Poly'

In [40]:
nwbfile_in.electrodes['group_name'].data[:]

array(['ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
      

In [41]:
device_idx = nwbfile_in.electrodes.group_name.data[:] == device

In [42]:
device_idx

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [47]:
nwbfile_in.electrodes['location'].data[device_idx]

array(['AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD'], dtype=object)

In [46]:
ch_ids = np.array([int(ch) for ch in nwbfile_in.electrodes['location'].data[device_idx]])

ValueError: invalid literal for int() with base 10: 'AUD'

In [5]:
nwbfile_in.electrodes.to_dataframe()

x   y   z  imp location  \
id                              
0   NaN NaN NaN  NaN      AUD   
1   NaN NaN NaN  NaN      AUD   
2   NaN NaN NaN  NaN      AUD   
3   NaN NaN NaN  NaN      AUD   
4   NaN NaN NaN  NaN      AUD   
..   ..  ..  ..  ...      ...   
123 NaN NaN NaN  NaN      AUD   
124 NaN NaN NaN  NaN      AUD   
125 NaN NaN NaN  NaN      AUD   
126 NaN NaN NaN  NaN      AUD   
127 NaN NaN NaN  NaN      AUD   

                                             filtering  \
id                                                       
0    The signal is low pass filtered at 45 percent ...   
1    The signal is low pass filtered at 45 percent ...   
2    The signal is low pass filtered at 45 percent ...   
3    The signal is low pass filtered at 45 percent ...   
4    The signal is low pass filtered at 45 percent ...   
..                                                 ...   
123  The signal is low pass filtered at 45 percent ...   
124  The signal is low pass filtered at 45 percent ...   
125  The signal is low pass filtered at 45 percent ...   
126  The signal is low pass filtered at 45 percent ...   
127  The signal is low pass filtered at 45 percent ...   

                                                 group group_name   rel_x  \
id                                                                          
0    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  3000.0   
1    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  2600.0   
2    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  3000.0   
3    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  2600.0   
4    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  3000.0   
..                                                 ...        ...     ...   
123  ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  2600.0   
124  ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  3000.0   
125  ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  2600.0   
126  ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  3000.0   
127  ECoG pynwb.ecephys.ElectrodeGroup at 0x1406289...       ECoG  2600.0   

      rel_y  rel_z  
id                  
0     800.0    0.0  
1     800.0    0.0  
2    1000.0    0.0  
3    1000.0    0.0  
4    1200.0    0.0  
..      ...    ...  
123   200.0    0.0  
124   400.0    0.0  
125   400.0    0.0  
126   600.0    0.0  
127   600.0    0.0  

[128 rows x 11 columns]

In [20]:
ch_ids = np.array([int(ch) for ch in nwbfile_in.electrodes.location.data[device_idx]])

ValueError: invalid literal for int() with base 10: ''

In [22]:
nwbfile_in.electrodes.location.data[:]

array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', ''], dtype=object)

# TRIAL STIM_START

In [83]:
nwb.trials

trials pynwb.epoch.TimeIntervals at 0x140628935949136
Fields:
  colnames: ['start_time' 'stop_time' 'sb' 'frq' 'amp']
  columns: (
    start_time <class 'hdmf.common.table.VectorData'>,
    stop_time <class 'hdmf.common.table.VectorData'>,
    sb <class 'hdmf.common.table.VectorData'>,
    frq <class 'hdmf.common.table.VectorData'>,
    amp <class 'hdmf.common.table.VectorData'>
  )
  description: experimental trials
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

In [84]:
df = nwb.trials.to_dataframe()
# df = df[df["sb"] == "s"]
df_s = df[df["sb"] == "s"]
df_s

start_time  stop_time sb    frq amp
id                                      
1      7.980483   8.030483  s    500   6
3      8.280515   8.330515  s   3175   6
5      8.580506   8.630506  s  12699   8
7      8.880497   8.930497  s    794   6
9      9.180488   9.230488  s  32000   4
..          ...        ... ..    ...  ..
591   96.480911  96.530911  s  12699   6
593   96.780902  96.830902  s   8000   6
595   97.080934  97.130934  s   1260   6
597   97.380925  97.430925  s  20159   4
599   97.680916  97.730916  s   2000   6

[300 rows x 5 columns]

In [118]:
onsets = df_s.iloc[:, [0,2]]
onsets

start_time sb
id                
1      7.980483  s
3      8.280515  s
5      8.580506  s
7      8.880497  s
9      9.180488  s
..          ... ..
591   96.480911  s
593   96.780902  s
595   97.080934  s
597   97.380925  s
599   97.680916  s

[300 rows x 2 columns]

In [96]:
stim_markers = onsets['start_time'].to_list()

In [97]:
fs = nwbfile_in.acquisition['ECoG'].rate

In [98]:
# fs_stim_delay = .25* fs

In [99]:
# marker_onsets = [int(x*fs+fs_stim_delay) for x in markers]

In [114]:
stim_onsets = [int(x*fs) for x in stim_markers]

In [120]:
stim_start = np.array(stim_onsets)
stim_start

array([  95765,   99366,  102966,  106565,  110165,  113766,  117366,
        120966,  124565,  128166,  131766,  135366,  138965,  142566,
        146166,  149766,  153366,  156966,  160566,  164166,  167766,
        171366,  174966,  178566,  182166,  185766,  189366,  192966,
        196566,  200166,  203766,  207366,  210966,  214566,  218166,
        221766,  225366,  228966,  232566,  236166,  239766,  243366,
        246966,  250566,  254166,  257766,  261366,  264966,  268566,
        272166,  275766,  279366,  282966,  286566,  290166,  293766,
        297366,  300967,  304566,  308166,  311766,  315367,  318966,
        322566,  326166,  329767,  333367,  336966,  340566,  344167,
        347767,  351367,  354966,  358567,  362167,  365767,  369366,
        372967,  376567,  380167,  383767,  387367,  390967,  394567,
        398167,  401767,  405367,  408967,  412567,  416167,  419767,
        423367,  426967,  430567,  434167,  437767,  441367,  444967,
        448567,  452

# TRIAL STIM_STOP

In [103]:
df = nwb.trials.to_dataframe()
# df = df[df["sb"] == "s"]
df_s = df[df["sb"] == "s"]
df_s

start_time  stop_time sb    frq amp
id                                      
1      7.980483   8.030483  s    500   6
3      8.280515   8.330515  s   3175   6
5      8.580506   8.630506  s  12699   8
7      8.880497   8.930497  s    794   6
9      9.180488   9.230488  s  32000   4
..          ...        ... ..    ...  ..
591   96.480911  96.530911  s  12699   6
593   96.780902  96.830902  s   8000   6
595   97.080934  97.130934  s   1260   6
597   97.380925  97.430925  s  20159   4
599   97.680916  97.730916  s   2000   6

[300 rows x 5 columns]

In [117]:
offsets = df_s.iloc[:, [1,2]]
offsets

stop_time sb
id               
1     8.030483  s
3     8.330515  s
5     8.630506  s
7     8.930497  s
9     9.230488  s
..         ... ..
591  96.530911  s
593  96.830902  s
595  97.130934  s
597  97.430925  s
599  97.730916  s

[300 rows x 2 columns]

In [112]:
stim_mrks = offsets['stop_time'].to_list()

In [113]:
stim_offsets = [int(x*fs) for x in stim_mrks]

In [119]:
stim_stop = np.array(stim_offsets)
stim_stop

array([  96365,   99966,  103566,  107165,  110765,  114366,  117966,
        121566,  125165,  128766,  132366,  135966,  139565,  143166,
        146766,  150366,  153966,  157566,  161166,  164766,  168366,
        171966,  175566,  179166,  182766,  186366,  189966,  193566,
        197166,  200766,  204366,  207966,  211566,  215166,  218766,
        222366,  225966,  229566,  233166,  236766,  240366,  243966,
        247566,  251166,  254766,  258366,  261966,  265566,  269166,
        272766,  276366,  279966,  283566,  287166,  290766,  294366,
        297966,  301567,  305166,  308766,  312366,  315967,  319566,
        323166,  326766,  330367,  333967,  337566,  341166,  344767,
        348367,  351967,  355566,  359167,  362767,  366367,  369966,
        373567,  377167,  380767,  384367,  387967,  391567,  395167,
        398767,  402367,  405967,  409567,  413167,  416767,  420367,
        423967,  427567,  431167,  434767,  438367,  441967,  445567,
        449167,  452

# BASELINE BASE_START

In [121]:
df = nwb.trials.to_dataframe()
# df = df[df["sb"] == "b"]
df_b = df[df["sb"] == "b"]
df_b

start_time   stop_time sb    frq  amp
id                                        
0      0.000000    7.930483  b  500.0  6.0
2      8.080483    8.160483  b    500    6
4      8.380515    8.460515  b   3175    6
6      8.680506    8.760506  b  12699    8
8      8.980497    9.060497  b    794    6
..          ...         ... ..    ...  ...
594   96.880902   96.960902  b   8000    6
596   97.180934   97.260934  b   1260    6
598   97.480925   97.560925  b  20159    4
600   97.780916   97.860916  b   2000    6
601   97.860916  101.669929  b   2000    6

[302 rows x 5 columns]

In [123]:
b_onsets = df_b.iloc[:, [0,2]]
b_onsets

start_time sb
id                
0      0.000000  b
2      8.080483  b
4      8.380515  b
6      8.680506  b
8      8.980497  b
..          ... ..
594   96.880902  b
596   97.180934  b
598   97.480925  b
600   97.780916  b
601   97.860916  b

[302 rows x 2 columns]

In [125]:
base_markers = b_onsets['start_time'].to_list()

In [126]:
base_onsets = [int(x*fs) for x in base_markers]

In [128]:
base_start = np.array(base_onsets)
base_start

array([      0,   96965,  100566,  104166,  107765,  111365,  114966,
        118566,  122166,  125765,  129366,  132966,  136566,  140165,
        143766,  147366,  150966,  154566,  158166,  161766,  165366,
        168966,  172566,  176166,  179766,  183366,  186966,  190566,
        194166,  197766,  201366,  204966,  208566,  212166,  215766,
        219366,  222966,  226566,  230166,  233766,  237366,  240966,
        244566,  248166,  251766,  255366,  258966,  262566,  266166,
        269766,  273366,  276966,  280566,  284166,  287766,  291366,
        294966,  298566,  302167,  305766,  309366,  312966,  316567,
        320166,  323766,  327366,  330967,  334567,  338166,  341766,
        345367,  348967,  352567,  356166,  359767,  363367,  366967,
        370566,  374167,  377767,  381367,  384967,  388567,  392167,
        395767,  399367,  402967,  406567,  410167,  413767,  417367,
        420967,  424567,  428167,  431767,  435367,  438967,  442567,
        446167,  449

# BASELINE BASE_STOP

In [129]:
df = nwb.trials.to_dataframe()
# df = df[df["sb"] == "b"]
df_b = df[df["sb"] == "b"]
df_b

start_time   stop_time sb    frq  amp
id                                        
0      0.000000    7.930483  b  500.0  6.0
2      8.080483    8.160483  b    500    6
4      8.380515    8.460515  b   3175    6
6      8.680506    8.760506  b  12699    8
8      8.980497    9.060497  b    794    6
..          ...         ... ..    ...  ...
594   96.880902   96.960902  b   8000    6
596   97.180934   97.260934  b   1260    6
598   97.480925   97.560925  b  20159    4
600   97.780916   97.860916  b   2000    6
601   97.860916  101.669929  b   2000    6

[302 rows x 5 columns]

In [130]:
b_offsets = df_b.iloc[:, [1,2]]
b_offsets

stop_time sb
id                
0      7.930483  b
2      8.160483  b
4      8.460515  b
6      8.760506  b
8      9.060497  b
..          ... ..
594   96.960902  b
596   97.260934  b
598   97.560925  b
600   97.860916  b
601  101.669929  b

[302 rows x 2 columns]

In [131]:
base_mrks = b_offsets['stop_time'].to_list()

In [132]:
base_offsets = [int(x*fs) for x in base_mrks]

In [133]:
base_stop = np.array(base_offsets)
base_stop

array([  95165,   97925,  101526,  105126,  108725,  112325,  115926,
        119526,  123126,  126725,  130326,  133926,  137526,  141125,
        144726,  148326,  151926,  155526,  159126,  162726,  166326,
        169926,  173526,  177126,  180726,  184326,  187926,  191526,
        195126,  198726,  202326,  205926,  209526,  213126,  216726,
        220326,  223926,  227526,  231126,  234726,  238326,  241926,
        245526,  249126,  252726,  256326,  259926,  263526,  267126,
        270726,  274326,  277926,  281526,  285126,  288726,  292326,
        295926,  299526,  303127,  306726,  310326,  313926,  317527,
        321126,  324726,  328326,  331927,  335527,  339126,  342726,
        346327,  349927,  353527,  357126,  360727,  364327,  367927,
        371526,  375127,  378727,  382327,  385927,  389527,  393127,
        396727,  400327,  403927,  407527,  411127,  414727,  418327,
        421927,  425527,  429127,  432727,  436327,  439927,  443527,
        447127,  450

In [11]:
data = nwbfile_in.acquisition['ECoG'].data

In [43]:
data.shape[0]

978944

In [7]:
mark_data = nwbfile_in.stimulus['recorded_mark'].data
len(mark_data)

KeyError: 'recorded_mark'

In [129]:
mark_fs = nwbfile_in.stimulus['recorded_mark'].rate
mark_fs

12207.03125

In [52]:
mark_offset = 0.25

In [53]:
stim_duration = 0.1

In [56]:
mark_fs

12207.03125

Vanessa Practice

In [44]:
end_time = data.shape[0] / fs

In [50]:
# np.arange(0.5, end_time, 1.0)

In [128]:
stim_dur_samp = stim_duration*mark_fs
stim_dur_samp

1220.703125

In [59]:
mark_threshold = 0.3

In [158]:
idk = mark_data[:] > mark_threshold
idk.shape

(980992,)

In [167]:
thresh_crossings = np.diff( (idk).astype('int'), axis=0 )

In [163]:
thresh_crossings.shape

(980991,)

In [134]:
new_thresh_crossings = np.r_[idk[0], thresh_crossings].cumsum()

In [221]:
stim_onsets = np.where(thresh_crossings > 0.5)[0] + 1
stim_onsets

array([212035, 224242, 236449, 248656, 260863, 273071, 285278, 297485,
       309692, 321899, 334106, 346313, 358520, 370727, 382934, 395141,
       407349, 419556, 431763, 443970, 456177, 468384, 480591, 492798,
       505005, 517212, 529420, 541627, 553834, 566041, 578248, 590455,
       602662, 614869, 627076, 639283, 651490, 663698, 675905, 688112,
       700319, 712526, 724733, 736940, 749147, 761354, 773561, 785769,
       797976, 810183, 822390, 834597, 846804, 859011, 871218, 883425,
       895632, 907839, 920047])

In [181]:
real_stim_onsets = [stim_onsets[0]]
real_stim_onsets

[212035]

In [192]:
for stim_onset in stim_onsets[1:]:
        # Check that each stim onset is more than 2x the stimulus duration since the previous
        if stim_onset > real_stim_onsets[-1] + 2*stim_dur_samp:
            real_stim_onsets.append(stim_onset)

In [193]:
if len(real_stim_onsets) != 60:
        print("WARNING")

WARNING


In [220]:
markers = (real_stim_onsets / mark_fs)
markers

array([17.3699072 , 18.36990464, 19.36990208, 20.36989952, 21.36989696,
       22.36997632, 23.36997376, 24.3699712 , 25.36996864, 26.36996608,
       27.36996352, 28.36996096, 29.3699584 , 30.36995584, 31.36995328,
       32.36995072, 33.37003008, 34.37002752, 35.37002496, 36.3700224 ,
       37.37001984, 38.37001728, 39.37001472, 40.37001216, 41.3700096 ,
       42.37000704, 43.3700864 , 44.37008384, 45.37008128, 46.37007872,
       47.37007616, 48.3700736 , 49.37007104, 50.37006848, 51.37006592,
       52.37006336, 53.3700608 , 54.37014016, 55.3701376 , 56.37013504,
       57.37013248, 58.37012992, 59.37012736, 60.3701248 , 61.37012224,
       62.37011968, 63.37011712, 64.37019648, 65.37019392, 66.37019136,
       67.3701888 , 68.37018624, 69.37018368, 70.37018112, 71.37017856,
       72.370176  , 73.37017344, 74.37017088, 75.37025024])

In [169]:
markers.shape

(59,)

In [176]:
a = np.array([2,3,4])

In [177]:
np.insert(a, 0, 1)

array([1, 2, 3, 4])

In [196]:
np.insert(markers, 0, 16.369907)

array([16.369907  , 17.3699072 , 18.36990464, 19.36990208, 20.36989952,
       21.36989696, 22.36997632, 23.36997376, 24.3699712 , 25.36996864,
       26.36996608, 27.36996352, 28.36996096, 29.3699584 , 30.36995584,
       31.36995328, 32.36995072, 33.37003008, 34.37002752, 35.37002496,
       36.3700224 , 37.37001984, 38.37001728, 39.37001472, 40.37001216,
       41.3700096 , 42.37000704, 43.3700864 , 44.37008384, 45.37008128,
       46.37007872, 47.37007616, 48.3700736 , 49.37007104, 50.37006848,
       51.37006592, 52.37006336, 53.3700608 , 54.37014016, 55.3701376 ,
       56.37013504, 57.37013248, 58.37012992, 59.37012736, 60.3701248 ,
       61.37012224, 62.37011968, 63.37011712, 64.37019648, 65.37019392,
       66.37019136, 67.3701888 , 68.37018624, 69.37018368, 70.37018112,
       71.37017856, 72.370176  , 73.37017344, 74.37017088, 75.37025024])

In [12]:
chs_ordered = [
       81, 83, 85, 87, 89, 91, 93, 95, 97, 105, 98, 106, 114, 122, 113, 121,
       82, 84, 86, 88, 90, 92, 94, 96, 99, 107, 100, 108, 116, 124, 115, 123,
       66, 68, 70, 72, 74, 76, 78, 80, 101, 109, 102, 110, 118, 126, 117, 125,
       65, 67, 69, 71, 73, 75, 77, 79, 103, 111, 104, 112, 120, 128, 119, 127,
       63, 61, 59, 57, 55, 53, 51, 49, 25, 17, 26, 18, 10, 2, 9, 1,
       64, 62, 60, 58, 56, 54, 52, 50, 27, 19, 28, 20, 12, 4, 11, 3,
       48, 46, 44, 42, 40, 38, 36, 34, 29, 21, 30, 22, 14, 6, 13, 5,
       47, 45, 43, 41, 39, 37, 35, 33, 31, 23, 32, 24, 16, 8, 15, 7
       ]

In [18]:
shape_wanted = data.shape
new_data = np.empty((shape_wanted[0], shape_wanted[1]))

In [20]:
for i in np.arange(shape_wanted[1]):
    new_data[:, i] = data[:, (chs_ordered[i] - 1)]
print(new_data) 

[[-271. -262. -266. ... -158. -113. -181.]
 [-276. -263. -262. ... -152. -120. -193.]
 [-271. -257. -249. ... -201. -127. -220.]
 ...
 [  -6.   12.   40. ... -597. -556. -523.]
 [   1.   13.   37. ... -568. -530. -496.]
 [   3.   15.   35. ... -528. -500. -473.]]


In [22]:
new_data[0]

array([-271., -262., -266., -251., -411., -292., -273., -240., -223.,
       -111., -214., -174., -222.,  185., -189., -216., -255., -216.,
       -336., -485., -361., -319., -303., -262., -225., -113., -221.,
       -104., -219.,   -2., -224., -201., -208., -120., -321., -402.,
       -395., -183., -387., -361., -100., -222., -217., -186., -204.,
         33., -201., -223., -381., -362., -390., -409., -376., -383.,
       -401., -379., -118., -243., -174., -238., -277.,  -17., -209.,
       -202.,  -74.,  -84.,  -97.,  -75.,  -82.,  -73.,  -79.,  -85.,
        -96., -109., -105., -100., -162., -129., -110., -178.,  -51.,
        -76.,  -95.,  -84.,  -50.,  -62., -119.,  -99., -116., -133.,
       -105., -113., -177., -109., -130., -180.,  -84.,  -49., -110.,
        -91., -131., -106., -127.,  -89., -113., -120., -129.,  -98.,
       -155., -114., -113., -169.,  -94.,  -84., -113.,  -98., -120.,
        -98., -108., -106., -120., -109., -102., -102., -157., -158.,
       -113., -181.]

In [140]:
io.close()

In [24]:
one_timepoint = nwbfile_in.acquisition['ECoG'].data[:, :]

In [25]:
one_timepoint.shape

(17860806, 128)

In [28]:
17860806/nwbfile_in.acquisition['ECoG'].rate

1463.15722752

In [29]:
1463/60

24.383333333333333

In [ ]:
nwbfile_in.stimulus['recorded_mark']

In [30]:
io1 = NWBHDF5IO('/Users/macproizzy/Desktop/R56_B13/R56_B13.nwb', 'r')
nwbfile_in1 = io1.read()

In [31]:
nwbfile_in1

root pynwb.file.NWBFile at 0x140587758073216
Fields:
  acquisition: {
    Raw <class 'pynwb.ecephys.LFP'>
  }
  devices: {
    ECoG <class 'pynwb.device.Device'>,
    Poly <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    ECoG <class 'pynwb.ecephys.ElectrodeGroup'>,
    Poly <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experiment_description: wn2 Stimulus Experiment
  experimenter: ['Max Dougherty']
  file_create_date: [datetime.datetime(2020, 12, 1, 12, 54, 12, 164816, tzinfo=tzoffset(None, -28800))]
  identifier: R56_B13
  institution: Lawrence Berkeley National Laboratory
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  lab: Bouchard Lab
  notes: TODO
  pharmacology: TODO
  processing: {
    ECoG <class 'pynwb.base.ProcessingModule'>,
    Hilb_54bands <class 'pynwb.base.ProcessingModule'>,
    tMUA <class 'pynwb.base.ProcessingModule'>,
    tMUA_rate <class 'pynwb.base.ProcessingModule'>
 

In [38]:
nwbfile_in1.processing['Hilb_54bands'].data_interfaces

{'ECoG': ECoG pynwb.misc.DecompositionSeries at 0x140587755856320
 Fields:
   bands: bands <class 'hdmf.common.table.DynamicTable'>
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (29367, 128, 54), type "<f4">
   description: processed data
   metric: amplitude
   rate: 400.0
   resolution: 0.0
   source_timeseries: ECoG pynwb.ecephys.ElectricalSeries at 0x140587754326960
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (448099, 128), type "<f4">
   description: no description
   electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
   rate: 6103.515625
   resolution: 0.0
   starting_time: 0.0
   starting_time_unit: seconds
   unit: volts
 
   starting_time: 0.0
   starting_time_unit: seconds
   unit: no unit}

In [32]:
nwbfile_in1.acquisition['Raw']

Raw pynwb.ecephys.LFP at 0x140587758259264
Fields:
  electrical_series: {
    ECoG <class 'pynwb.ecephys.ElectricalSeries'>,
    Poly <class 'pynwb.ecephys.ElectricalSeries'>
  }

In [34]:
nwbfile_in1.acquisition['Raw']['Poly'].data

<HDF5 dataset "data": shape (1792394, 64), type "<f4">

In [ ]:
nwbfile_in1.processing['tMUA_rate'].data_interfaces['ECoG']