# NWB exploration

In [264]:
from pynwb import NWBHDF5IO
import numpy as np 

In [266]:
#change pathway as needed
io = NWBHDF5IO('/Users/vanessagutierrez/Desktop/NWB_Test/RVG06/RVG06_B03.nwb', 'r')
nwbfile_in = io.read()

In [243]:
nwbfile_in.electrode_groups['Poly']

Poly pynwb.ecephys.ElectrodeGroup at 0x140514418212528
Fields:
  description: 64-ch Poly from NeuroNexus
  device: Poly pynwb.device.Device at 0x140514418210320
Fields:
  manufacturer: NeuroNexus


In [218]:
df = nwbfile_in.trials.to_dataframe()
df = df[df["sb"] == "s"]
df

start_time  stop_time sb
id                           
0     17.619907  17.719907  s
2     18.619905  18.719905  s
4     19.619902  19.719902  s
6     20.619900  20.719900  s
8     21.619897  21.719897  s
10    22.619976  22.719976  s
12    23.619974  23.719974  s
14    24.619971  24.719971  s
16    25.619969  25.719969  s
18    26.619966  26.719966  s
20    27.619964  27.719964  s
22    28.619961  28.719961  s
24    29.619958  29.719958  s
26    30.619956  30.719956  s
28    31.619953  31.719953  s
30    32.619951  32.719951  s
32    33.620030  33.720030  s
34    34.620028  34.720028  s
36    35.620025  35.720025  s
38    36.620022  36.720022  s
40    37.620020  37.720020  s
42    38.620017  38.720017  s
44    39.620015  39.720015  s
46    40.620012  40.720012  s
48    41.620010  41.720010  s
50    42.620007  42.720007  s
52    43.620086  43.720086  s
54    44.620084  44.720084  s
56    45.620081  45.720081  s
58    46.620079  46.720079  s
60    47.620076  47.720076  s
62    48.620074  48.720074  s
64    49.620071  49.720071  s
66    50.620068  50.720068  s
68    51.620066  51.720066  s
70    52.620063  52.720063  s
72    53.620061  53.720061  s
74    54.620140  54.720140  s
76    55.620138  55.720138  s
78    56.620135  56.720135  s
80    57.620132  57.720132  s
82    58.620130  58.720130  s
84    59.620127  59.720127  s
86    60.620125  60.720125  s
88    61.620122  61.720122  s
90    62.620120  62.720120  s
92    63.620117  63.720117  s
94    64.620196  64.720196  s
96    65.620194  65.720194  s
98    66.620191  66.720191  s
100   67.620189  67.720189  s
102   68.620186  68.720186  s
104   69.620184  69.720184  s
106   70.620181  70.720181  s
108   71.620179  71.720179  s
110   72.620176  72.720176  s
112   73.620173  73.720173  s
114   74.620171  74.720171  s
116   75.620250  75.720250  s

In [222]:
onsets = df.iloc[:, [0,2]]

In [227]:
markers = onsets['start_time'].to_list()

In [229]:
marker_onsets = [int(x*fs+fs_stim_delay) for x in markers]

In [230]:
marker_onsets

[218138,
 230345,
 242552,
 254759,
 266966,
 279174,
 291381,
 303588,
 315795,
 328002,
 340209,
 352416,
 364623,
 376830,
 389037,
 401244,
 413452,
 425659,
 437866,
 450073,
 462280,
 474487,
 486694,
 498901,
 511108,
 523315,
 535523,
 547730,
 559937,
 572144,
 584351,
 596558,
 608765,
 620972,
 633179,
 645386,
 657593,
 669801,
 682008,
 694215,
 706422,
 718629,
 730836,
 743043,
 755250,
 767457,
 779664,
 791872,
 804079,
 816286,
 828493,
 840700,
 852907,
 865114,
 877321,
 889528,
 901735,
 913942,
 926150]

In [228]:
fs_stim_delay = .25* fs

In [11]:
data = nwbfile_in.acquisition['ECoG'].data

In [43]:
data.shape[0]

978944

In [40]:
fs = nwbfile_in.acquisition['ECoG'].rate
fs

12207.03125

In [123]:
mark_data = nwbfile_in.stimulus['recorded_mark'].data
len(mark_data)

980992

In [129]:
mark_fs = nwbfile_in.stimulus['recorded_mark'].rate
mark_fs

12207.03125

In [52]:
mark_offset = 0.25

In [53]:
stim_duration = 0.1

In [56]:
mark_fs

12207.03125

Vanessa Practice

In [44]:
end_time = data.shape[0] / fs

In [50]:
# np.arange(0.5, end_time, 1.0)

In [128]:
stim_dur_samp = stim_duration*mark_fs
stim_dur_samp

1220.703125

In [59]:
mark_threshold = 0.3

In [158]:
idk = mark_data[:] > mark_threshold
idk.shape

(980992,)

In [167]:
thresh_crossings = np.diff( (idk).astype('int'), axis=0 )

In [163]:
thresh_crossings.shape

(980991,)

In [134]:
new_thresh_crossings = np.r_[idk[0], thresh_crossings].cumsum()

In [221]:
stim_onsets = np.where(thresh_crossings > 0.5)[0] + 1
stim_onsets

array([212035, 224242, 236449, 248656, 260863, 273071, 285278, 297485,
       309692, 321899, 334106, 346313, 358520, 370727, 382934, 395141,
       407349, 419556, 431763, 443970, 456177, 468384, 480591, 492798,
       505005, 517212, 529420, 541627, 553834, 566041, 578248, 590455,
       602662, 614869, 627076, 639283, 651490, 663698, 675905, 688112,
       700319, 712526, 724733, 736940, 749147, 761354, 773561, 785769,
       797976, 810183, 822390, 834597, 846804, 859011, 871218, 883425,
       895632, 907839, 920047])

In [181]:
real_stim_onsets = [stim_onsets[0]]
real_stim_onsets

[212035]

In [192]:
for stim_onset in stim_onsets[1:]:
        # Check that each stim onset is more than 2x the stimulus duration since the previous
        if stim_onset > real_stim_onsets[-1] + 2*stim_dur_samp:
            real_stim_onsets.append(stim_onset)

In [193]:
if len(real_stim_onsets) != 60:
        print("WARNING")

WARNING


In [220]:
markers = (real_stim_onsets / mark_fs)
markers

array([17.3699072 , 18.36990464, 19.36990208, 20.36989952, 21.36989696,
       22.36997632, 23.36997376, 24.3699712 , 25.36996864, 26.36996608,
       27.36996352, 28.36996096, 29.3699584 , 30.36995584, 31.36995328,
       32.36995072, 33.37003008, 34.37002752, 35.37002496, 36.3700224 ,
       37.37001984, 38.37001728, 39.37001472, 40.37001216, 41.3700096 ,
       42.37000704, 43.3700864 , 44.37008384, 45.37008128, 46.37007872,
       47.37007616, 48.3700736 , 49.37007104, 50.37006848, 51.37006592,
       52.37006336, 53.3700608 , 54.37014016, 55.3701376 , 56.37013504,
       57.37013248, 58.37012992, 59.37012736, 60.3701248 , 61.37012224,
       62.37011968, 63.37011712, 64.37019648, 65.37019392, 66.37019136,
       67.3701888 , 68.37018624, 69.37018368, 70.37018112, 71.37017856,
       72.370176  , 73.37017344, 74.37017088, 75.37025024])

In [169]:
markers.shape

(59,)

In [176]:
a = np.array([2,3,4])

In [177]:
np.insert(a, 0, 1)

array([1, 2, 3, 4])

In [196]:
np.insert(markers, 0, 16.369907)

array([16.369907  , 17.3699072 , 18.36990464, 19.36990208, 20.36989952,
       21.36989696, 22.36997632, 23.36997376, 24.3699712 , 25.36996864,
       26.36996608, 27.36996352, 28.36996096, 29.3699584 , 30.36995584,
       31.36995328, 32.36995072, 33.37003008, 34.37002752, 35.37002496,
       36.3700224 , 37.37001984, 38.37001728, 39.37001472, 40.37001216,
       41.3700096 , 42.37000704, 43.3700864 , 44.37008384, 45.37008128,
       46.37007872, 47.37007616, 48.3700736 , 49.37007104, 50.37006848,
       51.37006592, 52.37006336, 53.3700608 , 54.37014016, 55.3701376 ,
       56.37013504, 57.37013248, 58.37012992, 59.37012736, 60.3701248 ,
       61.37012224, 62.37011968, 63.37011712, 64.37019648, 65.37019392,
       66.37019136, 67.3701888 , 68.37018624, 69.37018368, 70.37018112,
       71.37017856, 72.370176  , 73.37017344, 74.37017088, 75.37025024])

In [12]:
chs_ordered = [
       81, 83, 85, 87, 89, 91, 93, 95, 97, 105, 98, 106, 114, 122, 113, 121,
       82, 84, 86, 88, 90, 92, 94, 96, 99, 107, 100, 108, 116, 124, 115, 123,
       66, 68, 70, 72, 74, 76, 78, 80, 101, 109, 102, 110, 118, 126, 117, 125,
       65, 67, 69, 71, 73, 75, 77, 79, 103, 111, 104, 112, 120, 128, 119, 127,
       63, 61, 59, 57, 55, 53, 51, 49, 25, 17, 26, 18, 10, 2, 9, 1,
       64, 62, 60, 58, 56, 54, 52, 50, 27, 19, 28, 20, 12, 4, 11, 3,
       48, 46, 44, 42, 40, 38, 36, 34, 29, 21, 30, 22, 14, 6, 13, 5,
       47, 45, 43, 41, 39, 37, 35, 33, 31, 23, 32, 24, 16, 8, 15, 7
       ]

In [18]:
shape_wanted = data.shape
new_data = np.empty((shape_wanted[0], shape_wanted[1]))

In [20]:
for i in np.arange(shape_wanted[1]):
    new_data[:, i] = data[:, (chs_ordered[i] - 1)]
print(new_data) 

[[-271. -262. -266. ... -158. -113. -181.]
 [-276. -263. -262. ... -152. -120. -193.]
 [-271. -257. -249. ... -201. -127. -220.]
 ...
 [  -6.   12.   40. ... -597. -556. -523.]
 [   1.   13.   37. ... -568. -530. -496.]
 [   3.   15.   35. ... -528. -500. -473.]]


In [22]:
new_data[0]

array([-271., -262., -266., -251., -411., -292., -273., -240., -223.,
       -111., -214., -174., -222.,  185., -189., -216., -255., -216.,
       -336., -485., -361., -319., -303., -262., -225., -113., -221.,
       -104., -219.,   -2., -224., -201., -208., -120., -321., -402.,
       -395., -183., -387., -361., -100., -222., -217., -186., -204.,
         33., -201., -223., -381., -362., -390., -409., -376., -383.,
       -401., -379., -118., -243., -174., -238., -277.,  -17., -209.,
       -202.,  -74.,  -84.,  -97.,  -75.,  -82.,  -73.,  -79.,  -85.,
        -96., -109., -105., -100., -162., -129., -110., -178.,  -51.,
        -76.,  -95.,  -84.,  -50.,  -62., -119.,  -99., -116., -133.,
       -105., -113., -177., -109., -130., -180.,  -84.,  -49., -110.,
        -91., -131., -106., -127.,  -89., -113., -120., -129.,  -98.,
       -155., -114., -113., -169.,  -94.,  -84., -113.,  -98., -120.,
        -98., -108., -106., -120., -109., -102., -102., -157., -158.,
       -113., -181.]

In [24]:
one_timepoint = nwbfile_in.acquisition['ECoG'].data[:, :]

In [25]:
one_timepoint.shape

(17860806, 128)

In [28]:
17860806/nwbfile_in.acquisition['ECoG'].rate

1463.15722752

In [29]:
1463/60

24.383333333333333

In [ ]:
nwbfile_in.stimulus['recorded_mark']

In [30]:
io1 = NWBHDF5IO('/Users/macproizzy/Desktop/R56_B13/R56_B13.nwb', 'r')
nwbfile_in1 = io1.read()

In [31]:
nwbfile_in1

root pynwb.file.NWBFile at 0x140587758073216
Fields:
  acquisition: {
    Raw <class 'pynwb.ecephys.LFP'>
  }
  devices: {
    ECoG <class 'pynwb.device.Device'>,
    Poly <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    ECoG <class 'pynwb.ecephys.ElectrodeGroup'>,
    Poly <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experiment_description: wn2 Stimulus Experiment
  experimenter: ['Max Dougherty']
  file_create_date: [datetime.datetime(2020, 12, 1, 12, 54, 12, 164816, tzinfo=tzoffset(None, -28800))]
  identifier: R56_B13
  institution: Lawrence Berkeley National Laboratory
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  lab: Bouchard Lab
  notes: TODO
  pharmacology: TODO
  processing: {
    ECoG <class 'pynwb.base.ProcessingModule'>,
    Hilb_54bands <class 'pynwb.base.ProcessingModule'>,
    tMUA <class 'pynwb.base.ProcessingModule'>,
    tMUA_rate <class 'pynwb.base.ProcessingModule'>
 

In [38]:
nwbfile_in1.processing['Hilb_54bands'].data_interfaces

{'ECoG': ECoG pynwb.misc.DecompositionSeries at 0x140587755856320
 Fields:
   bands: bands <class 'hdmf.common.table.DynamicTable'>
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (29367, 128, 54), type "<f4">
   description: processed data
   metric: amplitude
   rate: 400.0
   resolution: 0.0
   source_timeseries: ECoG pynwb.ecephys.ElectricalSeries at 0x140587754326960
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (448099, 128), type "<f4">
   description: no description
   electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
   rate: 6103.515625
   resolution: 0.0
   starting_time: 0.0
   starting_time_unit: seconds
   unit: volts
 
   starting_time: 0.0
   starting_time_unit: seconds
   unit: no unit}

In [32]:
nwbfile_in1.acquisition['Raw']

Raw pynwb.ecephys.LFP at 0x140587758259264
Fields:
  electrical_series: {
    ECoG <class 'pynwb.ecephys.ElectricalSeries'>,
    Poly <class 'pynwb.ecephys.ElectricalSeries'>
  }

In [34]:
nwbfile_in1.acquisition['Raw']['Poly'].data

<HDF5 dataset "data": shape (1792394, 64), type "<f4">

In [ ]:
nwbfile_in1.processing['tMUA_rate'].data_interfaces['ECoG']