# NWB exploration

In [1]:
from pynwb import NWBHDF5IO
import numpy as np 

In [32]:
#change pathway as needed
io = NWBHDF5IO('/Users/vanessagutierrez/Desktop/NWB_Test/RVG16/RVG16_B05.nwb', 'r')
nwbfile_in = io.read()

In [33]:
nwbfile_in

root pynwb.file.NWBFile at 0x140628044159392
Fields:
  acquisition: {
    ECoG <class 'pynwb.ecephys.ElectricalSeries'>,
    Poly <class 'pynwb.ecephys.ElectricalSeries'>
  }
  devices: {
    ECoG <class 'pynwb.device.Device'>,
    Poly <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    ECoG <class 'pynwb.ecephys.ElectrodeGroup'>,
    Poly <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experiment_description: This is an acute rat experiment. Auditory stimuli are played to an anesthsized rat and electrophysiological measurements are made auditory cortex
  experimenter: ['Vanessa Gutierrez']
  file_create_date: [datetime.datetime(2021, 9, 7, 13, 34, 37, 896650, tzinfo=tzoffset(None, -25200))]
  identifier: 05320762-101b-11ec-b9f7-aa665a133c20
  institution: Lawrence Berkeley National Lab
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  lab: Bouchard Lab
  notes: Gave ketamine then waited 10 mins ,

In [34]:
nwbfile_in.intervals['trials']['start_time'][:]

array([ 0.        ,  7.74766592,  7.84766592,  8.04765696,  8.14765696,
        8.347648  ,  8.447648  ,  8.64763904,  8.74763904,  8.94767104,
        9.04767104,  9.24766208,  9.34766208,  9.54765312,  9.64765312,
        9.84764416,  9.94764416, 10.14767616, 10.24767616, 10.4476672 ,
       10.5476672 , 10.74765824, 10.84765824, 11.04764928, 11.14764928,
       11.34768128, 11.44768128, 11.64767232, 11.74767232, 11.94766336,
       12.04766336, 12.24769536, 12.34769536, 12.5476864 , 12.6476864 ,
       12.84767744, 12.94767744, 13.14766848, 13.24766848, 13.44770048,
       13.54770048, 13.74769152, 13.84769152, 14.04768256, 14.14768256,
       14.3476736 , 14.4476736 , 14.6477056 , 14.7477056 , 14.94769664,
       15.04769664, 15.24768768, 15.34768768, 15.54767872, 15.64767872,
       15.84771072, 15.94771072, 16.14770176, 16.24770176, 16.4476928 ,
       16.5476928 , 16.74768384, 16.84768384, 17.04771584, 17.14771584,
       17.34770688, 17.44770688, 17.64769792, 17.74769792, 17.94

In [35]:
nwbfile_in.acquisition['ECoG'].data[:].shape

(1239166, 128)

In [36]:
nwbfile_in.stimulus

{'stim_onset_marks': stim_onset_marks pynwb.base.TimeSeries at 0x140628039993712
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (1261568,), type "<f4">
   description: Recorded mark that tracks stimulus onsets.
   rate: 12207.03125
   resolution: -1.0
   starting_time: 0.0
   starting_time_unit: seconds
   unit: Volts,
 'stim_waveform': stim_waveform pynwb.base.TimeSeries at 0x140628039993184
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (4800248,), type "<i2">
   description: Auditory stimulus waveform, aligned to neural recording.
   rate: 48000.0
   resolution: -1.0
   starting_time: 2.74766592
   starting_time_unit: seconds
   unit: Volts}

In [37]:
nwbfile_in.stimulus['stim_onset_marks']

stim_onset_marks pynwb.base.TimeSeries at 0x140628039993712
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (1261568,), type "<f4">
  description: Recorded mark that tracks stimulus onsets.
  rate: 12207.03125
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: Volts

In [38]:
nwbfile_in.stimulus['stim_waveform']

stim_waveform pynwb.base.TimeSeries at 0x140628039993184
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (4800248,), type "<i2">
  description: Auditory stimulus waveform, aligned to neural recording.
  rate: 48000.0
  resolution: -1.0
  starting_time: 2.74766592
  starting_time_unit: seconds
  unit: Volts

In [39]:
device = 'Poly'

In [40]:
nwbfile_in.electrodes['group_name'].data[:]

array(['ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
       'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG', 'ECoG',
      

In [41]:
device_idx = nwbfile_in.electrodes.group_name.data[:] == device

In [42]:
device_idx

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [47]:
nwbfile_in.electrodes['location'].data[device_idx]

array(['AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD', 'AUD',
       'AUD'], dtype=object)

In [46]:
ch_ids = np.array([int(ch) for ch in nwbfile_in.electrodes['location'].data[device_idx]])

ValueError: invalid literal for int() with base 10: 'AUD'

In [45]:
nwbfile_in.electrodes.to_dataframe()

x   y   z  imp location  \
id                              
0   NaN NaN NaN  NaN      AUD   
1   NaN NaN NaN  NaN      AUD   
2   NaN NaN NaN  NaN      AUD   
3   NaN NaN NaN  NaN      AUD   
4   NaN NaN NaN  NaN      AUD   
..   ..  ..  ..  ...      ...   
187 NaN NaN NaN  NaN      AUD   
188 NaN NaN NaN  NaN      AUD   
189 NaN NaN NaN  NaN      AUD   
190 NaN NaN NaN  NaN      AUD   
191 NaN NaN NaN  NaN      AUD   

                                             filtering  \
id                                                       
0    The signal is low pass filtered at 45 percent ...   
1    The signal is low pass filtered at 45 percent ...   
2    The signal is low pass filtered at 45 percent ...   
3    The signal is low pass filtered at 45 percent ...   
4    The signal is low pass filtered at 45 percent ...   
..                                                 ...   
187  The signal is low pass filtered at 45 percent ...   
188  The signal is low pass filtered at 45 percent ...   
189  The signal is low pass filtered at 45 percent ...   
190  The signal is low pass filtered at 45 percent ...   
191  The signal is low pass filtered at 45 percent ...   

                                                 group group_name    rel_x  \
id                                                                           
0    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406280...       ECoG  3000.00   
1    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406280...       ECoG  2600.00   
2    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406280...       ECoG  3000.00   
3    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406280...       ECoG  2600.00   
4    ECoG pynwb.ecephys.ElectrodeGroup at 0x1406280...       ECoG  3000.00   
..                                                 ...        ...      ...   
187  Poly pynwb.ecephys.ElectrodeGroup at 0x1406280...       Poly    11.25   
188  Poly pynwb.ecephys.ElectrodeGroup at 0x1406280...       Poly    11.25   
189  Poly pynwb.ecephys.ElectrodeGroup at 0x1406280...       Poly    11.25   
190  Poly pynwb.ecephys.ElectrodeGroup at 0x1406280...       Poly    11.25   
191  Poly pynwb.ecephys.ElectrodeGroup at 0x1406280...       Poly   -11.25   

      rel_y   rel_z  
id                   
0     800.0     0.0  
1     800.0     0.0  
2    1000.0     0.0  
3    1000.0     0.0  
4    1200.0     0.0  
..      ...     ...  
187     0.0  1080.0  
188     0.0   900.0  
189     0.0  1395.0  
190     0.0  1260.0  
191     0.0  1102.5  

[192 rows x 11 columns]

In [20]:
ch_ids = np.array([int(ch) for ch in nwbfile_in.electrodes.location.data[device_idx]])

ValueError: invalid literal for int() with base 10: ''

In [22]:
nwbfile_in.electrodes.location.data[:]

array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', ''], dtype=object)

In [85]:
nwbfile_in.trials

trials pynwb.epoch.TimeIntervals at 0x140482394036736
Fields:
  colnames: ['start_time' 'stop_time' 'sb' 'frq' 'amp']
  columns: (
    start_time <class 'hdmf.common.table.VectorData'>,
    stop_time <class 'hdmf.common.table.VectorData'>,
    sb <class 'hdmf.common.table.VectorData'>,
    frq <class 'hdmf.common.table.VectorData'>,
    amp <class 'hdmf.common.table.VectorData'>
  )
  description: experimental trials
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

In [102]:
df = nwbfile_in.trials.to_dataframe()
# df = df[df["sb"] == "s"]
df_s = df[df["sb"] == "s"]
df_s

start_time   stop_time sb    frq amp
id                                       
1     12.334735   12.384735  s    500   6
3     12.634726   12.684726  s   3175   6
5     12.934758   12.984758  s  12699   8
7     13.234749   13.284749  s    794   6
9     13.534740   13.584740  s  32000   4
..          ...         ... ..    ...  ..
591  100.835164  100.885164  s  12699   6
593  101.135196  101.185196  s   8000   6
595  101.435187  101.485187  s   1260   6
597  101.735178  101.785178  s  20159   4
599  102.035169  102.085169  s   2000   6

[300 rows x 5 columns]

In [95]:
nwbfile_in.trials and 'sb' in nwbfile_in.trials.colnames

True

In [94]:
'sb' in nwbfile_in.trials.colnames

True

In [222]:
onsets = df.iloc[:, [0,2]]

In [227]:
markers = onsets['start_time'].to_list()

In [229]:
marker_onsets = [int(x*fs+fs_stim_delay) for x in markers]

In [230]:
marker_onsets

[218138,
 230345,
 242552,
 254759,
 266966,
 279174,
 291381,
 303588,
 315795,
 328002,
 340209,
 352416,
 364623,
 376830,
 389037,
 401244,
 413452,
 425659,
 437866,
 450073,
 462280,
 474487,
 486694,
 498901,
 511108,
 523315,
 535523,
 547730,
 559937,
 572144,
 584351,
 596558,
 608765,
 620972,
 633179,
 645386,
 657593,
 669801,
 682008,
 694215,
 706422,
 718629,
 730836,
 743043,
 755250,
 767457,
 779664,
 791872,
 804079,
 816286,
 828493,
 840700,
 852907,
 865114,
 877321,
 889528,
 901735,
 913942,
 926150]

In [228]:
fs_stim_delay = .25* fs

In [11]:
data = nwbfile_in.acquisition['ECoG'].data

In [43]:
data.shape[0]

978944

In [40]:
fs = nwbfile_in.acquisition['ECoG'].rate
fs

12207.03125

In [123]:
mark_data = nwbfile_in.stimulus['recorded_mark'].data
len(mark_data)

980992

In [129]:
mark_fs = nwbfile_in.stimulus['recorded_mark'].rate
mark_fs

12207.03125

In [52]:
mark_offset = 0.25

In [53]:
stim_duration = 0.1

In [56]:
mark_fs

12207.03125

Vanessa Practice

In [44]:
end_time = data.shape[0] / fs

In [50]:
# np.arange(0.5, end_time, 1.0)

In [128]:
stim_dur_samp = stim_duration*mark_fs
stim_dur_samp

1220.703125

In [59]:
mark_threshold = 0.3

In [158]:
idk = mark_data[:] > mark_threshold
idk.shape

(980992,)

In [167]:
thresh_crossings = np.diff( (idk).astype('int'), axis=0 )

In [163]:
thresh_crossings.shape

(980991,)

In [134]:
new_thresh_crossings = np.r_[idk[0], thresh_crossings].cumsum()

In [221]:
stim_onsets = np.where(thresh_crossings > 0.5)[0] + 1
stim_onsets

array([212035, 224242, 236449, 248656, 260863, 273071, 285278, 297485,
       309692, 321899, 334106, 346313, 358520, 370727, 382934, 395141,
       407349, 419556, 431763, 443970, 456177, 468384, 480591, 492798,
       505005, 517212, 529420, 541627, 553834, 566041, 578248, 590455,
       602662, 614869, 627076, 639283, 651490, 663698, 675905, 688112,
       700319, 712526, 724733, 736940, 749147, 761354, 773561, 785769,
       797976, 810183, 822390, 834597, 846804, 859011, 871218, 883425,
       895632, 907839, 920047])

In [181]:
real_stim_onsets = [stim_onsets[0]]
real_stim_onsets

[212035]

In [192]:
for stim_onset in stim_onsets[1:]:
        # Check that each stim onset is more than 2x the stimulus duration since the previous
        if stim_onset > real_stim_onsets[-1] + 2*stim_dur_samp:
            real_stim_onsets.append(stim_onset)

In [193]:
if len(real_stim_onsets) != 60:
        print("WARNING")

WARNING


In [220]:
markers = (real_stim_onsets / mark_fs)
markers

array([17.3699072 , 18.36990464, 19.36990208, 20.36989952, 21.36989696,
       22.36997632, 23.36997376, 24.3699712 , 25.36996864, 26.36996608,
       27.36996352, 28.36996096, 29.3699584 , 30.36995584, 31.36995328,
       32.36995072, 33.37003008, 34.37002752, 35.37002496, 36.3700224 ,
       37.37001984, 38.37001728, 39.37001472, 40.37001216, 41.3700096 ,
       42.37000704, 43.3700864 , 44.37008384, 45.37008128, 46.37007872,
       47.37007616, 48.3700736 , 49.37007104, 50.37006848, 51.37006592,
       52.37006336, 53.3700608 , 54.37014016, 55.3701376 , 56.37013504,
       57.37013248, 58.37012992, 59.37012736, 60.3701248 , 61.37012224,
       62.37011968, 63.37011712, 64.37019648, 65.37019392, 66.37019136,
       67.3701888 , 68.37018624, 69.37018368, 70.37018112, 71.37017856,
       72.370176  , 73.37017344, 74.37017088, 75.37025024])

In [169]:
markers.shape

(59,)

In [176]:
a = np.array([2,3,4])

In [177]:
np.insert(a, 0, 1)

array([1, 2, 3, 4])

In [196]:
np.insert(markers, 0, 16.369907)

array([16.369907  , 17.3699072 , 18.36990464, 19.36990208, 20.36989952,
       21.36989696, 22.36997632, 23.36997376, 24.3699712 , 25.36996864,
       26.36996608, 27.36996352, 28.36996096, 29.3699584 , 30.36995584,
       31.36995328, 32.36995072, 33.37003008, 34.37002752, 35.37002496,
       36.3700224 , 37.37001984, 38.37001728, 39.37001472, 40.37001216,
       41.3700096 , 42.37000704, 43.3700864 , 44.37008384, 45.37008128,
       46.37007872, 47.37007616, 48.3700736 , 49.37007104, 50.37006848,
       51.37006592, 52.37006336, 53.3700608 , 54.37014016, 55.3701376 ,
       56.37013504, 57.37013248, 58.37012992, 59.37012736, 60.3701248 ,
       61.37012224, 62.37011968, 63.37011712, 64.37019648, 65.37019392,
       66.37019136, 67.3701888 , 68.37018624, 69.37018368, 70.37018112,
       71.37017856, 72.370176  , 73.37017344, 74.37017088, 75.37025024])

In [12]:
chs_ordered = [
       81, 83, 85, 87, 89, 91, 93, 95, 97, 105, 98, 106, 114, 122, 113, 121,
       82, 84, 86, 88, 90, 92, 94, 96, 99, 107, 100, 108, 116, 124, 115, 123,
       66, 68, 70, 72, 74, 76, 78, 80, 101, 109, 102, 110, 118, 126, 117, 125,
       65, 67, 69, 71, 73, 75, 77, 79, 103, 111, 104, 112, 120, 128, 119, 127,
       63, 61, 59, 57, 55, 53, 51, 49, 25, 17, 26, 18, 10, 2, 9, 1,
       64, 62, 60, 58, 56, 54, 52, 50, 27, 19, 28, 20, 12, 4, 11, 3,
       48, 46, 44, 42, 40, 38, 36, 34, 29, 21, 30, 22, 14, 6, 13, 5,
       47, 45, 43, 41, 39, 37, 35, 33, 31, 23, 32, 24, 16, 8, 15, 7
       ]

In [18]:
shape_wanted = data.shape
new_data = np.empty((shape_wanted[0], shape_wanted[1]))

In [20]:
for i in np.arange(shape_wanted[1]):
    new_data[:, i] = data[:, (chs_ordered[i] - 1)]
print(new_data) 

[[-271. -262. -266. ... -158. -113. -181.]
 [-276. -263. -262. ... -152. -120. -193.]
 [-271. -257. -249. ... -201. -127. -220.]
 ...
 [  -6.   12.   40. ... -597. -556. -523.]
 [   1.   13.   37. ... -568. -530. -496.]
 [   3.   15.   35. ... -528. -500. -473.]]


In [22]:
new_data[0]

array([-271., -262., -266., -251., -411., -292., -273., -240., -223.,
       -111., -214., -174., -222.,  185., -189., -216., -255., -216.,
       -336., -485., -361., -319., -303., -262., -225., -113., -221.,
       -104., -219.,   -2., -224., -201., -208., -120., -321., -402.,
       -395., -183., -387., -361., -100., -222., -217., -186., -204.,
         33., -201., -223., -381., -362., -390., -409., -376., -383.,
       -401., -379., -118., -243., -174., -238., -277.,  -17., -209.,
       -202.,  -74.,  -84.,  -97.,  -75.,  -82.,  -73.,  -79.,  -85.,
        -96., -109., -105., -100., -162., -129., -110., -178.,  -51.,
        -76.,  -95.,  -84.,  -50.,  -62., -119.,  -99., -116., -133.,
       -105., -113., -177., -109., -130., -180.,  -84.,  -49., -110.,
        -91., -131., -106., -127.,  -89., -113., -120., -129.,  -98.,
       -155., -114., -113., -169.,  -94.,  -84., -113.,  -98., -120.,
        -98., -108., -106., -120., -109., -102., -102., -157., -158.,
       -113., -181.]

In [24]:
one_timepoint = nwbfile_in.acquisition['ECoG'].data[:, :]

In [25]:
one_timepoint.shape

(17860806, 128)

In [28]:
17860806/nwbfile_in.acquisition['ECoG'].rate

1463.15722752

In [29]:
1463/60

24.383333333333333

In [ ]:
nwbfile_in.stimulus['recorded_mark']

In [30]:
io1 = NWBHDF5IO('/Users/macproizzy/Desktop/R56_B13/R56_B13.nwb', 'r')
nwbfile_in1 = io1.read()

In [31]:
nwbfile_in1

root pynwb.file.NWBFile at 0x140587758073216
Fields:
  acquisition: {
    Raw <class 'pynwb.ecephys.LFP'>
  }
  devices: {
    ECoG <class 'pynwb.device.Device'>,
    Poly <class 'pynwb.device.Device'>
  }
  electrode_groups: {
    ECoG <class 'pynwb.ecephys.ElectrodeGroup'>,
    Poly <class 'pynwb.ecephys.ElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  experiment_description: wn2 Stimulus Experiment
  experimenter: ['Max Dougherty']
  file_create_date: [datetime.datetime(2020, 12, 1, 12, 54, 12, 164816, tzinfo=tzoffset(None, -28800))]
  identifier: R56_B13
  institution: Lawrence Berkeley National Laboratory
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  lab: Bouchard Lab
  notes: TODO
  pharmacology: TODO
  processing: {
    ECoG <class 'pynwb.base.ProcessingModule'>,
    Hilb_54bands <class 'pynwb.base.ProcessingModule'>,
    tMUA <class 'pynwb.base.ProcessingModule'>,
    tMUA_rate <class 'pynwb.base.ProcessingModule'>
 

In [38]:
nwbfile_in1.processing['Hilb_54bands'].data_interfaces

{'ECoG': ECoG pynwb.misc.DecompositionSeries at 0x140587755856320
 Fields:
   bands: bands <class 'hdmf.common.table.DynamicTable'>
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (29367, 128, 54), type "<f4">
   description: processed data
   metric: amplitude
   rate: 400.0
   resolution: 0.0
   source_timeseries: ECoG pynwb.ecephys.ElectricalSeries at 0x140587754326960
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (448099, 128), type "<f4">
   description: no description
   electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
   rate: 6103.515625
   resolution: 0.0
   starting_time: 0.0
   starting_time_unit: seconds
   unit: volts
 
   starting_time: 0.0
   starting_time_unit: seconds
   unit: no unit}

In [32]:
nwbfile_in1.acquisition['Raw']

Raw pynwb.ecephys.LFP at 0x140587758259264
Fields:
  electrical_series: {
    ECoG <class 'pynwb.ecephys.ElectricalSeries'>,
    Poly <class 'pynwb.ecephys.ElectricalSeries'>
  }

In [34]:
nwbfile_in1.acquisition['Raw']['Poly'].data

<HDF5 dataset "data": shape (1792394, 64), type "<f4">

In [ ]:
nwbfile_in1.processing['tMUA_rate'].data_interfaces['ECoG']